65 implement web api for afrr service
diversiwaver/aFRR-NET pull request #79
Opened 2022-12-16 08:07 UTC by martin-vlacil

Web API Controllers for Bids and Signals and DTOs as well as testing

2022-12-16 08:41 UTC, WrexBG commented
Depends on #79 
Waiting for that to be merged
+ Doesn't have a version tag yet so that should be added before merging

2022-12-20 10:14 UTC, mette-thorhauge requested changes
The code has been commented, except for everything related to the Data access layer, as this is being changed in another project, and then implemented in this one as well. This also goes for the tests for the data access layer.

2022-12-20 10:14 UTC, mette-thorhauge commented on aFRR-Service/WebAPI/Controllers/BidsController.cs
> +        IEnumerable<BidDTO> bidDtos = DTOConverter<Bid, BidDTO>.FromList(bids);
```suggestion
        
        IEnumerable<BidDTO> bidDtos = DTOConverter<Bid, BidDTO>.FromList(bids);
```

2022-12-20 10:14 UTC, mette-thorhauge commented on aFRR-Service/WebAPI/Controllers/SignalsController.cs
> +        _logger.LogInformation("Converting Signal to SignalDTO.");
```suggestion
       
         _logger.LogInformation("Converting Signal to SignalDTO.");
```

2022-12-20 11:10 UTC, WrexBG commented on aFRR-Service/TestWebAPI/Tests/TestBidController.cs
> +        Assert.That(actionResult, Is.Not.Null, "Action result was null");
Approved with: Commit https://github.com/diversiwaver/aFRR-NET/pull/79/commits/ede8e0aa313fbfbeebc407e8140fcf99b3f6a5be

2022-12-20 13:00 UTC, WrexBG approved these changes
Looks good

2022-12-21 12:34 UTC, martin-vlacil reviewed
gut

2022-12-21 12:39 UTC, mette-thorhauge approved these changes
It looks great now!

2022-12-21 12:39 UTC, merged